#!/usr/bin/env bash
# NonoClaw 构建脚本 — 支持日常迭代 / 最终发布两种模式
#
# 用法:
#   bash scripts/build.sh            # 默认: 日常迭代 (release-fast, ~3-5 min)
#   bash scripts/build.sh release    # 最终发布 (full LTO, ~20 min+)
#   bash scripts/build.sh dev --mold # 日常迭代 + mold 链接器 (~1-2 min)
#
# 参数:
#   dev        日常迭代 (默认) — 无 LTO, 并行 codegen，产出略大但功能一致
#   release    最终发布 — LTO + 单 codegen-unit + strip，最小二进制
#   --mold     安装并使用 mold 快速链接器 (需 sudo/网络)
#   --no-frontend  跳过前端构建
#   --no-test      跳过测试

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RUST_DIR="$ROOT/rust"
FRONTEND_DIR="$ROOT/frontend"

MODE="dev"            # dev | release
INSTALL_MOLD=false
SKIP_FRONTEND=false
SKIP_TEST=false

# ── Parse args ──────────────────────────────────────────────────────────
for arg in "$@"; do
    case "$arg" in
        dev|release) MODE="$arg" ;;
        --mold)      INSTALL_MOLD=true ;;
        --no-frontend) SKIP_FRONTEND=true ;;
        --no-test)   SKIP_TEST=true ;;
        -h|--help)
            head -14 "$0" | tail -12
            exit 0
            ;;
        *)
            echo "未知参数: $arg (try --help)" >&2
            exit 1
            ;;
    esac
done

echo "╔══════════════════════════════════════════╗"
echo "║  NonoClaw Build                         ║"
echo "╠══════════════════════════════════════════╣"

if [[ "$MODE" == "release" ]]; then
    PROFILE="release"
    echo "║  Mode:  RELEASE  (LTO + optimize)       ║"
else
    PROFILE="release-fast"
    echo "║  Mode:  DEV      (fast, no LTO)         ║"
fi
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Step 0: Ensure mold linker (optional) ───────────────────────────────
if $INSTALL_MOLD; then
    echo "━━━ Step 0: mold linker ━━━"
    if command -v mold &>/dev/null; then
        echo "  ✓ mold $(mold --version 2>&1 | head -1) 已安装"
    else
        echo "  安装 mold ..."
        if sudo apt-get install -y mold 2>/dev/null; then
            echo "  ✓ mold 安装成功 (apt)"
        elif command -v curl &>/dev/null; then
            # 从 GitHub 下载（apt 失败时走这条，不依赖 apt）
            MOLD_VER="2.36.0"
            echo "  apt 安装失败，从 GitHub 下载 mold v${MOLD_VER} ..."
            ARCH=$(uname -m)
            TAR="mold-${MOLD_VER}-${ARCH}-linux.tar.gz"
            URL="https://github.com/rui314/mold/releases/download/v${MOLD_VER}/${TAR}"
            curl -fsSL "$URL" -o "/tmp/${TAR}"
            tar xzf "/tmp/${TAR}" -C /tmp
            sudo cp "/tmp/mold-${MOLD_VER}-${ARCH}-linux/bin/mold" /usr/local/bin/
            sudo cp "/tmp/mold-${MOLD_VER}-${ARCH}-linux/lib/mold/mold-wrapper.so" /usr/local/lib/
            rm -f "/tmp/${TAR}" "/tmp/mold-${MOLD_VER}-${ARCH}-linux" 2>/dev/null || true
            echo "  ✓ mold $(mold --version 2>&1 | head -1) 安装完成"
        else
            echo "  ✗ 无法安装 mold (需要 apt 或 curl)。跳过。"
        fi
    fi

    # Write .cargo/config.toml so Rust uses mold for this target
    CARGO_CFG="$RUST_DIR/.cargo/config.toml"
    mkdir -p "$(dirname "$CARGO_CFG")"
    if command -v mold &>/dev/null; then
        cat > "$CARGO_CFG" <<'CARGOEOF'
# Generated by scripts/build.sh --mold
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
CARGOEOF
        echo "  ✓ .cargo/config.toml 已配置 mold"
    fi
    echo ""
fi

# ── Step 1: 测试 ────────────────────────────────────────────────────────
if ! $SKIP_TEST; then
    echo "━━━ Step 1: 测试 ━━━"
    (
        cd "$RUST_DIR"
        cargo test --workspace 2>&1 | grep -E "test result:" || echo "  (all passed)"
    )
    echo ""
fi

# ── Step 2: 前端构建 ────────────────────────────────────────────────────
if ! $SKIP_FRONTEND; then
    echo "━━━ Step 2: 前端构建 ━━━"
    (
        cd "$FRONTEND_DIR"
        echo "  类型检查 ..."
        npx tsc --noEmit 2>&1
        echo "  构建 ..."
        npm run build 2>&1 | tail -3
    )
    echo ""
fi

# ── Step 3: Rust 编译 ───────────────────────────────────────────────────
echo "━━━ Step 3: Rust 编译 (profile=$PROFILE) ━━━"
(
    cd "$RUST_DIR"
    START=$(date +%s)
    cargo build --profile "$PROFILE" 2>&1
    END=$(date +%s)
    ELAPSED=$((END - START))
    MIN=$((ELAPSED / 60))
    SEC=$((ELAPSED % 60))
    echo ""
    echo "  ✓ 编译完成 (耗时 ${MIN}m${SEC}s)"

    # Resolve binary path
    if [[ "$PROFILE" == "release" ]]; then
        BIN="$RUST_DIR/target/release/nonoclaw"
    else
        BIN="$RUST_DIR/target/release-fast/nonoclaw"
    fi

    if [[ -f "$BIN" ]]; then
        SIZE=$(ls -lh "$BIN" | awk '{print $5}')
        echo "  Binary: $BIN  ($SIZE)"
    fi
)
echo ""

# ── Done ────────────────────────────────────────────────────────────────
if $INSTALL_MOLD; then
cat <<EOF
╔══════════════════════════════════════════╗
║  构建成功 ✓                             ║
╠══════════════════════════════════════════╣
║  mold 已就绪 — 后续构建将自动使用       ║
╚══════════════════════════════════════════╝
EOF
else
cat <<'EOF'
╔══════════════════════════════════════════╗
║  构建成功 ✓                             ║
╠══════════════════════════════════════════╣
║  Tip: bash scripts/build.sh dev --mold   ║
║  安装 mold 链接器可再快 2-3 倍           ║
╚══════════════════════════════════════════╝
EOF
fi
